/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package id.danielniko.simpleGradleJunit;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {


}
